["install-toolchains-for-sync-markdown"]
description = "Install Rust toolchain for synchronizing markdown"
depends = ["install-nightly-toolchain"]

["sync:markdown"]
description = "Synchronize Markdown files with Rust doc comments"
usage = '''
flag "--check" help="Run cargo-sync-rdme in check mode"
flag "--allow-dirty" help="Sync Markdown files even if the target file is dirty"
flag "--allow-no-vcs" help="Sync Markdown files even if no VCS found"
flag "--locked" help="Assert that `Cargo.lock` will remain unchanged."
'''
depends = ["install-toolchains-for-sync-markdown"]
raw_args = true
quiet = true
run = '''
#!/usr/bin/env bash
set -euxo pipefail
cargo sync-rdme --workspace "$@"
'''

["format:markdown"]
description = "Format Markdown files"
usage = '''
flag "--check" help="Run rumdl in check mode"
'''
raw_args = true
quiet = true
run = '''
#!/usr/bin/env bash
set -euxo pipefail
rumdl format "$@"
'''

["lint:markdown"]
description = "Lint Markdown files"
run = "rumdl check"
