name: CD

env:
  CRATE_TYPE: "bin"

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main
  pull_request:

jobs:
  cd:
    strategy:
      matrix:
        crate_type: [ bin ]
    uses: gifnksm/rust-template/.github/workflows/reusable-cd.yml@main
    with:
      upload-dist-archive: ${{ matrix.crate_type }}
